### ISSUE TITLE
MacOS chainerrl support

### ISSUE THREAD

**Issue by AndKram** [spMohanty/marLo#17]
python3 -m examples.multiagent_chainer_test_DQN --turn_based --rollouts 10 --mission mob_chase.xml
Stub out registration as newer version of gym
/usr/local/lib/python3.7/site-packages/chainer/_environment_check.py:38: UserWarning: Accelerate has been detected as a NumPy backend library.
vecLib, which is a part of Accelerate, is known not to work correctly with Chainer.
We recommend using other BLAS libraries such as OpenBLAS.
For details of the issue, please see
https://docs.chainer.org/en/stable/tips.html#mnist-example-does-not-converge-in-cpu-mode-on-mac-os-x.

Also note that Chainer does not officially support Mac OS X.
Please use it at your own risk.

  ''')  # NOQA
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/v-andkra/Coding/marLo/examples/multiagent_chainer_test_DQN.py", line 1, in <module>
    from marlo import experiments
  File "/Users/v-andkra/Coding/marLo/marlo/experiments/__init__.py", line 3, in <module>
    from marlo.experiments.train_agent import train_agent  # NOQA
  File "/Users/v-andkra/Coding/marLo/marlo/experiments/train_agent.py", line 15, in <module>
    from chainerrl.misc.ask_yes_no import ask_yes_no
  File "/usr/local/lib/python3.7/site-packages/chainerrl/__init__.py", line 3, in <module>
    from chainerrl import agents  # NOQA
  File "/usr/local/lib/python3.7/site-packages/chainerrl/agents/__init__.py", line 1, in <module>
    from chainerrl.agents.a3c import A3C  # NOQA
  File "/usr/local/lib/python3.7/site-packages/chainerrl/agents/a3c.py", line 17
    from chainerrl.misc import async
                                   ^
SyntaxError: invalid syntax

**Comment by AndKram** [comment]
Pip3 installed chainerrl on MacOS breaks. Seems to be fixed on git hub:

https://github.com/chainer/chainerrl/commit/2322e5a626ce4539f1e72cb34f6fb4f280bedbf8

by renaming async to asyn_
